name: KEDA Scale self hosted

on:
  workflow_dispatch:

env:
  AZ_STORAGE_ACCOUNT: aca2keda2scaler126

jobs:
  #External Job to create and associate workflow with a unique Job ID on Azure queue to scale up KEDA
  scale-keda-queue-up:
    runs-on: ubuntu-latest
    steps:
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: scale up self hosted
      id: scaleJob
      run: |
        OUTPUT=$(az storage message put --queue-name gh-runner-scaler --content ${{ github.job }} --account-name ${{ env.AZ_STORAGE_ACCOUNT }})
        ID=$(echo "$OUTPUT" | grep "id" | sed 's/^.*: //' | sed 's/,*$//g')
        POP=$(echo "$OUTPUT" | grep "popReceipt" | sed 's/^.*: //' | sed 's/,*$//g')
        echo "::set-output name=scaleJobId::$ID"
        echo "::set-output name=scaleJobPop::$POP"

    outputs:
      scaleJobId: ${{ steps.scaleJob.outputs.scaleJobId }}
      scaleJobPop: ${{ steps.scaleJob.outputs.scaleJobPop }}

  #Subsequent Jobs runs-on [self-hosted]. Job1, Job2, JobN etc etc
  testRunner:
    needs: scale-keda-queue-up
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Display Terraform Version
      run: terraform --version
    - name: Display Azure-CLI Version
      run: az --version
    
    #Remove unique Job ID on Azure queue as final step to scale down KEDA
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: scale down self hosted
      run: |
        az storage message delete --id ${{needs.scaleJob.outputs.scaleJobId}} --pop-receipt ${{needs.scaleJob.outputs.scaleJobPop}} --queue-name gh-runner-scaler --account-name ${{ env.AZ_STORAGE_ACCOUNT }}