name: Local runner test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      run: |
        python3 -m pip install --upgrade pip
        pip3 install terraform
    - name: Display Terraform Version
      run: terraform --version
    - name: Display Azure-CLI Version
      run: az --version